### ISSUE TITLE
Clarify Xbox section

### ISSUE THREAD

**Issue by TheTrueCoder** [mikeroyal/Unreal-Engine-Guide#16]
I saw you have the link to the Xbox Dev mode under the Xbox section of your wonderful guide.
I would recommend probably removing it because Unreal Engine does not officially support the UWP app format, or you could add an extra bit explaining that while it can't be used with the official version of Unreal, there are some custom branches of Unreal that add support for the format including the one released by Microsoft's Xbox team ages ago (https://github.com/MICROSOFT-XBOX-ATG/MICROSOFT_UWP_UNREAL), and the one ported forward by a community member that is still very old (UE 4.24) (https://github.com/EmmettJnr/UnrealEngine). These obviously require building the engine from source.
You can still use other engines with UWP support like Unity or Godot, just not Unreal (I believe Tim Sweeny has objections to UWP).

I just want to help people who might see dev mode save them hours diving down the rabbit hole that is trying to make an Xbox game, and the TLDR is that you can't really do it in Unreal Engine without the closed, NDA protected SDKs from Microsoft/Epic Games that you get with ID@Xbox and similar arrangements.

**Comment by mikeroyal** [comment]
Thank you for pointing this out. I have removed the link from the Xbox section.
